ticket-list:
  # Set this to false if you want tickets to be deleted.
  delete-on-leave: true

  # Append on words.
  #   trigger:
  #   - some
  #   - words
  trigger:
  - water
  - fire
  - lava
  - grief
  - mod
  - portal
  
  # Set this to true whether you want ticket information logged.
  log-ticket-information: false

reminder:
  # Set this to true to enable ticket reminders.
  enable: false
  # Interval is set to 10min (600sec) by default.
  interval: 600

namethatmob:
  # The words you want to blacklist
  blacklisted-words:
  - fagget
  - fuck
  - dick
  - bitch
  - retard
  - penis
  - vagina
  
  # The amount of letters you want limited in name tag
  character-limit: 16
  
currency:
  vault-enable: true
  currency-cost-per-nametag: 2600
  
# Character limit set to 8 by default.
character-limit: 8
# Black list words that you don't want users to set.
blacklisted-words:
- fuck
- fagget
- dick
- vagina
