name: BigBadCraft
main: me.bigbadhenz.bigbadcraft.ticket.Main
version: 2.0
website: www.bigbadcraft.net
softdepend: [Vault]
commands:
  helpop:
    description: Submits a ticket.
  ticket:
    description: A list of commands.
    permission: staffticket.mod
    permission-message: You do not have <permission>
    default: op
  mytickets:
    description: Lists your unclaimed tickets.
  warn:
    description: Warns a user.
    permission: bigbadcraft.staff
    permission-message: You do not have <permission>
    default: op
  namemob:
    description: Provides modified nametab with a given argument.
    permission: bigbadcraft.nametag
    permission-message: You do not have <permission>
    default: op
  ride:
    description: Rides specified player.
    permission: bigbadcraft.ride
    permission-message: You do not have <permission>
    default: op